providers:
- base_url: http://localhost:8002
  key: ''
  name: localhost
- base_url: https://api.mapbox.com/valhalla/v1
  key: pk.eyJ1Ijoibmlsc25vbGRlIiwiYSI6ImNqc2V4Mmg2NjEycm4zeXRieW12dHZpYXUifQ.dRO2j6OjtAPQcLteel3t-A
  name: Mapbox
- base_url: http://116.202.182.93:8002
  key: ''
  name: temp
